language: python

matrix:
  # This will launch a separate build for each Python version you add
  # Feel free to add extra environment variables as needed
  include:
    - python: 3.8

install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest
