version: "3.7"
services:
  headshot-creator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Path/to/input:/code/input
      - /Path/to/output:/code/output
    command: >-
      python main.py
        --output_size='(400,500)'
        --padding='(40,70)'
        --confidence_threshold=0.95